
-- Création de la base cIara Mobility

-- Table vehicule
CREATE TABLE vehicule (
  id_vehicule INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  marque VARCHAR(50) NOT NULL,
  modele VARCHAR(50) NOT NULL,
  type_vehicule VARCHAR(30) NOT NULL,
  autonomie_km INTEGER NOT NULL CHECK (autonomie_km >= 0),
  etat VARCHAR(20) NOT NULL CHECK (
    etat IN ('Disponible','En location','En maintenance','Hors service')
  ),
  ville VARCHAR(50) NOT NULL
);

-- Table station
CREATE TABLE station (
  id_station INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom VARCHAR(80) NOT NULL,
  ville VARCHAR(50) NOT NULL
);

-- Table client
CREATE TABLE client (
  id_client INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom VARCHAR(80) NOT NULL,
  prenom VARCHAR(80) NOT NULL,
  email VARCHAR(120) NOT NULL UNIQUE
);

-- Table location
CREATE TABLE location (
  id_location INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date_debut TIMESTAMP NOT NULL,
  date_fin TIMESTAMP NOT NULL,
  id_client INTEGER NOT NULL,
  id_vehicule INTEGER NOT NULL,
  id_station_depart INTEGER NOT NULL,
  id_station_arrivee INTEGER NOT NULL,

  CONSTRAINT chk_dates CHECK (date_fin > date_debut),

  FOREIGN KEY (id_client) REFERENCES client(id_client),
  FOREIGN KEY (id_vehicule) REFERENCES vehicule(id_vehicule),
  FOREIGN KEY (id_station_depart) REFERENCES station(id_station),
  FOREIGN KEY (id_station_arrivee) REFERENCES station(id_station)
);
